name: test_env
channels:
  - conda-forge
dependencies:
  - mypy=1.6.1
  - pyarrow
  - python=3.8
  - pip
  - pip:
    - types-paramiko
    - types-requests
    - types-tqdm
    - types-paramiko
    - types-PyYAML
    - types-ujson
