name: test_env
channels:
  - conda-forge
dependencies:
  - mypy=1.4.1
  - pyarrow
  - python=3.9
  - pip
  - pip:
    - types-paramiko
    - types-requests
    - types-tqdm
    - types-paramiko
    - types-PyYAML
    - types-ujson
