name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - pandas
  - xarray
  - zarr
  - pytest<8
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
  - s3fs
  - requests
  - moto <5
  - sqlalchemy<2
  - flask
  - dask-expr
